import assert from 'node:assert/strict';
import { spawn, spawnSync } from 'node:child_process';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';
import { createServer } from 'node:net';
import { RelayState } from '../../relay/src/index.ts';
const candidates = ['openssl', ...(process.platform === 'win32' && process.env.ProgramFiles ? [join(process.env.ProgramFiles, 'Git', 'mingw64', 'bin', 'openssl.exe')] : [])];
const openssl = candidates.find(candidate => spawnSync(candidate, ['version'], { stdio: 'ignore' }).status === 0);
test('installed Cordis private-config variant owns HTTPS/WSS lifecycle, preserves injected services and rejects mixed config', { skip: !process.env.DSH_MOBILE_CORDIS_MODULE || !openssl, timeout: 15000 }, async t => {
  const dir = mkdtempSync(join(tmpdir(), 'dsh-mobile-plugin-relay-')); t.after(() => rmSync(dir, { recursive: true, force: true }));
  const state = new RelayState(join(dir, 'relay.sqlite')); const owner = state.provisionRoute(); state.close();
  const reserve = createServer(); await new Promise<void>(resolve => reserve.listen(0, '127.0.0.1', resolve)); const port = (reserve.address() as { port: number }).port; await new Promise<void>(resolve => reserve.close(() => resolve()));
  for (const [name, host, san] of [['outer', '127.0.0.1', 'IP:127.0.0.1'], ['inner', `h-${owner.routeId}.dsh.invalid`, `DNS:h-${owner.routeId}.dsh.invalid`]]) assert.equal(spawnSync(openssl!, ['req', '-x509', '-newkey', 'rsa:2048', '-sha256', '-nodes', '-days', '1', '-keyout', join(dir, name! + '.key'), '-out', join(dir, name! + '.pem'), '-subj', `/CN=${host}`, '-addext', `subjectAltName=${san}`], { stdio: 'ignore' }).status, 0);
  const child = spawn(process.execPath, [fileURLToPath(new URL('./fixtures/plugin-relay-child.ts', import.meta.url)), dir, process.env.DSH_MOBILE_CORDIS_MODULE!, owner.routeId, owner.connectorToken, String(port)], { env: { ...process.env, NODE_EXTRA_CA_CERTS: join(dir, 'outer.pem') }, stdio: ['ignore', 'pipe', 'pipe'] });
  let output = ''; child.stdout.on('data', data => { output += data.toString(); }); child.stderr.on('data', data => { output += data.toString(); });
  const result = await new Promise<number | null>((resolve, reject) => { child.once('error', reject); child.once('exit', resolve); }); assert.equal(result, 0, output); assert.match(output, /PASS installed Cordis configPath/);
});
